Select * from SPRINKLER_GROUP;

--Query 1 to get functional status =true and group given

SELECT SPRINKLERID , WATERCONSUMPTION FROM SPRINKLER_GROUP
WHERE FUNCTIONALSTATUS ='true' AND LOCATION = 'North';

--INSERT INTO SPRINKLER_SCHEDULE VALUES ('b','1N',to_date('1998/05/31:1:00:00AM', 'yyyy/mm/dd:hh:mi:ssam')
--,to_date('1998/05/31:1:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),to_date('1998/05/31:12:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),6);

SELECT * FROM SPRINKLER_SCHEDULE;

SELECT G.LOCATION,G.SPRINKLERID,S.STARTTIME ,S.ENDTIME ,S.TOTALHOURS,S.TOTALDAYS,S.WATERFLOW FROM SPRINKLER_SCHEDULE S , SPRINKLER_GROUP G
WHERE S.SPRINKLERID = G.SPRINKLERID AND  G.LOCATION ='North' 
AND S.scheduleStartDate <= '05-SEP-09' AND S.SCHEDULEENDDATE >= '05-SEP-09'


AND to_char( S.scheduleStartDate, 'MON' )=  'SEP';




