Select * from SPRINKLER_GROUP;

--Query 1 to get functional status =true and group given

SELECT SPRINKLERID , WATERCONSUMPTION FROM SPRINKLER_GROUP
WHERE FUNCTIONALSTATUS ='true' AND LOCATION = 'North';

--INSERT INTO SPRINKLER_SCHEDULE VALUES ('b','1N',to_date('1998/05/31:1:00:00AM', 'yyyy/mm/dd:hh:mi:ssam')
--,to_date('1998/05/31:1:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),to_date('1998/05/31:12:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),6);

SELECT * FROM SPRINKLER_SCHEDULE;

SELECT SPRINKLERID,LOCATION,STARTTIME,ENDTIME  FROM SPRINKLER_SCHEDULE 
WHERE LOCATION = 'North'
AND SCHEDULESTARTDATE <= '05-AUG-16' AND SCHEDULEENDDATE >= '05-AUG-16';

SELECT SCHEDULEMONTH ,SUM(TOTALWATER 









